name: Release

on:
  workflow_call:
    inputs:
      install:
        type: string
        required: false
        default: npm ci
    secrets:
      gh_token: 
        required: true
      npm_token:
        required: true

jobs:
  has:
    name: Check Secrets
    runs-on: ubuntu-latest
    steps:
    - id: secrets
      env:
        npm_token: ${{ secrets.npm_token }}
        gh_token: ${{ secrets.gh_token }}
      if: ${{ env.npm_token != '' && env.gh_token != '' }}
      run:
        echo "::set-output name=secrets::1"
    outputs:
      secrets: ${{ steps.secrets.outputs.secrets }}

  release:
    name: Release
    needs: has
    if: ${{ needs.has.outputs.secrets }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0
          persist-credentials: false

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: ${{ inputs.install }}

      - name: Create release pull request or publish to npm
        id: changesets
        uses: changesets/action@master
        with:
          title: Release Tracking
          # This expects you to have a script called release which does a build for your packages and calls changeset publish
          publish: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.gh_token }}
          NPM_TOKEN: ${{ secrets.npm_token }}
