name: Release

on:
  workflow_call:
    inputs:
      install:
        type: string
        required: false
        default: npm ci
    secrets:
      gh_token: 
        required: true
      npm_token:
        required: true

jobs:
  secrets:
    name: Check Secrets
    runs-on: ubuntu-latest
    outputs:
      secrets: ${{ steps.has-secrets.outputs.secrets }}
    steps:
      - name: Check Secrets
        id: has-secrets
        env:
          HAS_GITHUB_TOKEN: ${{ secrets.gh_token != '' }}
          HAS_NPM_TOKEN: ${{ secrets.npm_token != '' }}
        if: env.HAS_GITHUB_TOKEN == 'true' && env.HAS_NPM_TOKEN == 'true'
        run:
          echo "::set-output name=secrets::1"

  release-canary:
    name: Canary
    runs-on: ubuntu-latest
    needs: secrets
    if: needs.secrets.outputs.secrets
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: ${{ inputs.install }}

      - name: Build
        run: npm run build --if-present

      - name: Create .npmrc
        run: |
          cat << EOF > "$HOME/.npmrc"
            //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF
        env:
          NPM_TOKEN: ${{ secrets.npm_token }}

      - name: Publish canary release
        run: |
          echo "$( jq '.version = "0.0.0"' package.json )" > package.json
          echo -e "---\n$( jq .name package.json ): patch\n---\n\nFake entry to force publishing" > .changeset/force-snapshot-release.md
          yarn changeset version --snapshot
          yarn changeset publish --tag canary
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}

      - name: Output canary version
        uses: actions/github-script@v4.0.2
        with:
          script: |
            const package = require(`${process.env.GITHUB_WORKSPACE}/package.json`)
            github.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.sha,
              state: 'success',
              context: `Published ${package.name}`,
              description: package.version,
              target_url: `https://unpkg.com/${package.name}@${package.version}/`
            })
