name: Release

on:
  workflow_call:
    inputs:
      install:
        type: string
        required: false
        default: npm ci
      title:
        type: string
        required: false
        default: Release tracking
    secrets:
      gh_token: 
        required: true
      npm_token:
        required: true

jobs:
  secrets:
    name: Check Secrets
    runs-on: ubuntu-latest
    outputs:
      secrets: ${{ steps.has-secrets.outputs.secrets }}
    steps:
      - name: Check Secrets
        id: has-secrets
        env:
          HAS_GITHUB_TOKEN: ${{ secrets.gh_token != '' }}
          HAS_NPM_TOKEN: ${{ secrets.npm_token != '' }}
        if: env.HAS_GITHUB_TOKEN == 'true' && env.HAS_NPM_TOKEN == 'true'
        run:
          echo "::set-output name=secrets::1"

  release:
    name: Release
    needs: secrets
    if: needs.secrets.outputs.secrets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0
          persist-credentials: false

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: ${{ inputs.install }}

      - name: Create release pull request or publish to npm
        id: changesets
        uses: changesets/action@master
        with:
          title: ${{ inputs.title }}
          # This expects you to have a script called release which does a build for your packages and calls changeset publish
          publish: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.gh_token }}
          NPM_TOKEN: ${{ secrets.npm_token }}
